on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Загрузка репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Установка Ruff
        run: pip install ruff

      - name: Проверка кода
        run: ruff check .

      - name: Проверка форматирования
        run: ruff format --check .
